NuevoComienzo/Controllers/RegistrarPersonaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuevoComienzo.Models;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;


namespace NuevoComienzo.Controllers
{

    public class RegistrarPersonaController : Controller
    {
        /// <summary>
        /// Estado e informacion de la sesion del administrador
        /// </summary>
        private readonly SignInManager<IdentityUser> SignInManager;
        private readonly UserManager<IdentityUser> UserManager;

        /// <summary>
        /// Contexto de la base de datos para hacer cambios a las tabnlas
        /// </summary>
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="context">Cpntexto de la base de datos a modificar</param>
        public RegistrarPersonaController(ApplicationDbContext context, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _context = context;
            SignInManager = signInManager;
            UserManager = userManager;
        }

        /// <summary>
        /// Metodo que muestra la vista con las tablas de personas
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            // Verifica si hay una sesion iniciada
            if (SignInManager.IsSignedIn(User))// Si hay sesion iniciada muestra las tablas de personas
            {
                var persona = _context.Persona.Include(p => p.TipoPersona);
                return View(await persona.ToListAsync());
            }
            else// Si no hay sesion iniciada redirecciona a la pagina principal
            {
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Metodo que muestra toda la informacion de la persona seleccionada en la lista
        /// </summary>
        /// <param name="id">Identificador privado de la persona</param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (SignInManager.IsSignedIn(User)) // Si hay una sesion iniciada de administrador
            {
                if (id == null)
                {
                    return NotFound();
                }
                // Obtiene la informacion relacionada a la persona de la base de datos
                var persona = await _context.Persona
                    .Include(p => p.Anotacion)
                    .Include(p => p.Direccion)
                    .Include(p => p.Identificador)
                    .Include(p => p.TipoPersona)
                    .Include(p => p.Identificador.TipoIdentificador)
                    .Include(p => p.Direccion.Distrito)
                    .Include(p => p.Direccion.Distrito.Canton)
                    .Include(p => p.Direccion.Distrito.Canton.Provincia)


                    .FirstOrDefaultAsync(m => m.PersonaId == id);
                if (persona == null)
                {
                    return NotFound();
                }

                // Cambia los valores a mostrar de las referencias de la persona por sus descripciones en lugar de su ID
                ViewData["TipoIdentificadorId"] = new SelectList(_context.Set<TipoIdentificador>(), "TipoIdentificadorId", "DescTipoIdentificador");
                ViewData["TipoPersonaId"] = new SelectList(_context.TipoPersona, "TipoPersonaId", "DescTipoPersona");
                ViewData["DistritoId"] = new SelectList(_context.Set<Distrito>(), "DistritoId", "Nombre");
                ViewData["CantonId"] = new SelectList(_context.Set<Distrito>(), "CantonId", "Nombre");
                ViewData["ProvinciaId"] = new SelectList(_context.Set<Distrito>(), "ProvinciaId", "Nombre");
                ViewData["DireccionId"] = new SelectList(_context.Set<Distrito>(), "DireccionId", "DescDireccion");


                return View(persona);
            }
            else // Si no hay sesion iniciada vuelve a la pagina principal
            {
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Metodo que devuelve la vista para agregar personas a la base de datos
        /// </summary>
        /// <returns>Vista de creacion de personas</returns>
        public ActionResult Create()
        {
            if (SignInManager.IsSignedIn(User)) // Si hay sesion iniciada
            {
                // Cambia los valores de las referencias a otras tablas por sus descripciones
                ViewData["TipoIdentificadorId"] = new SelectList(_context.Set<TipoIdentificador>(), "TipoIdentificadorId", "DescTipoIdentificador");
                ViewData["TipoPersonaId"] = new SelectList(_context.TipoPersona, "TipoPersonaId", "DescTipoPersona");
                ViewData["DistritoId"] = new SelectList(_context.Set<Distrito>(), "DistritoId", "Nombre");

                // Se instancia un View Model
                var vm = new RegistrarPersonaVM();
                return View();
            }
            else // Si no hay sesion iniciada se vuelve a la pagina principal
            {
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Metodo que obtiene los parametros ingresados en el formulario para 
        /// ingresar una persona a base de datos
        /// </summary>
        /// <param name="vm">View Model para mostrar los campos necesarios para
        /// agregar toda la informacion de la persona</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PrimerNombre,SegundoNombre,PrimerApellido,SegundoApellido,Sexo,DescDireccion,Medicamentos,DistritoId,Alergias,DiagnosticoAprendizaje,DiagnosticoPsicologico,ObservacionesSupervisor,IdentificadorId,TipoIdentificadorId,Correo,Telefono,TipoPersonaId,FechaNacimiento")]RegistrarPersonaVM vm)
        {
            if (SignInManager.IsSignedIn(User)) // Se verifica si hay sesion iniciada
            {
                try
                {
                    // Se instancia un objeto de tipo Direccion con los valores obtenidos del View Model
                    var direccion = new Direccion
                    {
                        DescDireccion = vm.DescDireccion,
                        DistritoId = vm.DistritoId,
                    };

                    // Se instancia un objeto de tipo Anotacion con los valores obtenidos del View Model
                    var anotacion = new Anotacion
                    {
                        Medicamentos = vm.Medicamentos,
                        Alergias = vm.Alergias,
                        DiagnosticoAprendizaje = vm.DiagnosticoAprendizaje,
                        DiagnosticoPsicologico = vm.DiagnosticoPsicologico,
                        ObservacionesSupervisor = vm.ObservacionesSupervisor
                    };

                    // Se instancia un objeto de tipo Identifiacdor con los valores obtenidos del View Model
                    var identificador = new Identificador
                    {
                        IdentificadorId = vm.IdentificadorId,
                        TipoIdentificadorId = vm.TipoIdentificadorId
                    };

                    // Se agregan objetos con estos valores a la base de datos
                    // Se agregan primero que persona para no incurrir en un error al agregar en base de datos a la persona
                    _context.Direccion.Add(direccion);
                    _context.Anotacion.Add(anotacion);
                    _context.Identificador.Add(identificador);

                    // Se instancia un objeto de tipo Persona con los valores obtenidos del View Model
                    var persona = new Persona
                    {
                        PrimerNombre = vm.PrimerNombre,
                        SegundoNombre = vm.SegundoNombre,
                        PrimerApellido = vm.PrimerApellido,
                        SegundoApellido = vm.SegundoApellido,
                        Sexo = vm.Sexo,
                        TipoPersonaId = vm.TipoPersonaId,
                        IdentificadorId = identificador.IdentificadorId, // Se usa el ID del identificador ya creado como llave foranea para el nuevo objeto de persona en base de datos
                        AnotacionId = anotacion.AnotacionId, // Se usa el ID de la anotacion ya creado como llave foranea para el nuevo objeto de persona en base de datos
                        Correo = vm.Correo,
                        Telefono = vm.Telefono,
                        FechaNacimiento = vm.FechaNacimiento,
                        DireccionId = direccion.DireccionId // Se usa el ID de la direccion ya creado como llave foranea para el nuevo objeto de persona en base de datos

                    };
                    // Se agrega a la persona a base de datos
                    _context.Persona.Add(persona);

                    // Se guardan los cambios en la base de datos
                    await _context.SaveChangesAsync();

                    // Se vuelve a la pagina de tablas de personas
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    // En caso de haber un error, se guarda para ser puesto en pantalla
                    ViewBag.ErrorMessage = e;
                    return View();
                }
            }
            else // Si no hay sesion iniciada se vuelve a la pagina principal
            {
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Metodo para obtener la informacion de base de datos necesaria para editar a la persona seleccionada

NuevoComienzo/Views/RegistrarPersona/Create.cshtml
@model NuevoComienzo.Models.RegistrarPersonaVM

@{
    ViewData["Title"] = "Registrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container" style="padding-top:10%;">

        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert-danger"> <p>Ha ocurrido un error! Intente de nuevo</p> <p>ERROR: @ViewBag.ErrorMessage</p> </div>
        }

        <h1>Registrar</h1>

        <h4>Persona</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="PrimerNombre" class="control-label">Primer Nombre</label>
                        <input asp-for="PrimerNombre" class="form-control" />
                        <span asp-validation-for="PrimerNombre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SegundoNombre" class="control-label">Segundo Nombre</label>
                        <input asp-for="SegundoNombre" class="form-control" />
                        <span asp-validation-for="SegundoNombre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PrimerApellido" class="control-label">Primer Apellido</label>
                        <input asp-for="PrimerApellido" class="form-control" />
                        <span asp-validation-for="PrimerApellido" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SegundoApellido" class="control-label">Segundo Apellido</label>
                        <input asp-for="SegundoApellido" class="form-control" />
                        <span asp-validation-for="SegundoApellido" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="IdentificadorId" class="control-label">Identificaci&oacute;n</label>
                        <input asp-for="IdentificadorId" class="form-control" />
                        <span asp-validation-for="IdentificadorId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TipoIdentificadorId" class="control-label">Tipo de Identificacion</label>
                        <select asp-for="TipoIdentificadorId" class="form-control" asp-items="ViewBag.TipoIdentificadorId"></select>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            Sexo
                            <div class="form-check-inline">
                                <input type="radio" class="form-check-input" asp-for="Sexo" value="M" /> M
                            </div>
                            <div class="form-check-inline">
                                <input type="radio" class="form-check-input" asp-for="Sexo" value="F" /> F
                            </div>
                        </label>
                    </div>
                    <div class="form-group">
                        <label asp-for="FechaNacimiento" class="control-label">Fecha de Nacimiento</label>
                        <input asp-for="FechaNacimiento" class="form-control" />
                        <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DescDireccion" class="control-label">Direcci&oacute;n</label>
                        <textarea asp-for="DescDireccion" rows="4" class="form-control"></textarea>
                        <span asp-validation-for="DescDireccion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DistritoId" class="control-label">Distrito</label>
                        <select asp-for="DistritoId" class="form-control" asp-items="ViewBag.DistritoId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Correo" class="control-label"></label>
                        <input asp-for="Correo" class="form-control" />
                        <span asp-validation-for="Correo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label">Tel&eacute;fono</label>
                        <input asp-for="Telefono" class="form-control" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TipoPersonaId" class="control-label">Rol</label>
                        <select asp-for="TipoPersonaId" class="form-control" asp-items="ViewBag.TipoPersonaId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Medicamentos" class="control-label">Medicamentos</label>
                        <textarea asp-for="Medicamentos" class="form-control"></textarea>
                        <span asp-validation-for="Medicamentos" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Alergias" class="control-label">Alergias</label>
                        <textarea asp-for="Alergias" class="form-control"></textarea>
                        <span asp-validation-for="Alergias" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DiagnosticoAprendizaje" class="control-label">Diagn&oacute;stico de Aprendizaje</label>
                        <textarea asp-for="DiagnosticoAprendizaje" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="DiagnosticoAprendizaje" class="text-danger "></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DiagnosticoPsicologico" class="control-label">Diagn&oacute;stico Psicol&oacute;gico</label>
                        <textarea asp-for="DiagnosticoPsicologico" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="DiagnosticoPsicologico" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ObservacionesSupervisor" class="control-label">Observaciones del Supervisor</label>
                        <textarea asp-for="ObservacionesSupervisor" rows="5" class="form-control"></textarea>
                        <span asp-validation-for="ObservacionesSupervisor" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Registrar" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Volver</a>
        </div>
    </div>

@if  (ViewBag.ErrorMessage != null)
{
    <div class="alert-danger"> <p>Ha ocurrido un error!</p> <p>ERROR: @ViewBag.ErrorMessage</p> </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NuevoComienzo/Views/RegistrarPersona/Index.cshtml
@model IEnumerable<NuevoComienzo.Models.Persona>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="container" style="padding-top:10%;">
        <h1>Ni&ntilde;os</h1>

        <p>
            <a asp-controller="RegistrarPersona" asp-action="Create">Registrar Nuevo</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        1<sup>er</sup> Nombre
                    </th>
                    <th>
                        2<sup>do</sup> Nombre
                    </th>
                    <th>
                        1<sup>er</sup> Apellido
                    </th>
                    <th>
                        2<sup>do</sup> Apellido
                    </th>
                    <th>
                        Identificaci&oacute;n
                    </th>
                    <th>
                        Sexo
                    </th>
                    <th>
                        Tel&eacute;fono
                    </th>
                    <th>
                        Correo
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    if (item.TipoPersonaId == 1)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PrimerNombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SegundoNombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PrimerApellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SegundoApellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdentificadorId)
                            </td>
                            <td>
                                @if (item.Sexo == "M")
                                {
                                    <p>M</p>
                                }
                                else
                                {
                                    <p>F</p>
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Correo)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.PersonaId">Editar</a> |
                                <a asp-action="Details" asp-route-id="@item.PersonaId">+Informaci&oacute;n</a> |
                                <a asp-action="Delete" asp-route-id="@item.PersonaId" style="color:red;">Borrar</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <h1>Padres</h1>

        <p>
            <a asp-controller="RegistrarPersona" asp-action="Create">Registrar Nuevo</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        1<sup>er</sup> Nombre
                    </th>
                    <th>
                        2<sup>do</sup> Nombre
                    </th>
                    <th>
                        1<sup>er</sup> Apellido
                    </th>
                    <th>
                        2<sup>do</sup> Apellido
                    </th>
                    <th>
                        Identificaci&oacute;n
                    </th>
                    <th>
                        Sexo
                    </th>
                    <th>
                        Tel&eacute;fono
                    </th>
                    <th>
                        Correo
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    if (item.TipoPersonaId == 3)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PrimerNombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SegundoNombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PrimerApellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SegundoApellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdentificadorId)
                            </td>
                            <td>
                                @if (item.Sexo == "M")
                                {
                                    <p>M</p>
                                }
                                else
                                {
                                    <p>F</p>
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Correo)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.PersonaId">Editar</a> |
                                <a asp-action="Details" asp-route-id="@item.PersonaId">+Informaci&oacute;n</a> |
                                <a asp-action="Delete" asp-route-id="@item.PersonaId" style="color:red;">Borrar</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <h1>Voluntarios</h1>

        <p>
            <a asp-controller="RegistrarPersona" asp-action="Create">Registrar Nuevo</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        1<sup>er</sup> Nombre
                    </th>
                    <th>
                        2<sup>do</sup> Nombre
                    </th>
                    <th>
                        1<sup>er</sup> Apellido
                    </th>
                    <th>
                        2<sup>do</sup> Apellido
                    </th>
                    <th>
                        Identificaci&oacute;n
                    </th>
                    <th>
                        Sexo
                    </th>
                    <th>
                        Tel&eacute;fono
                    </th>
                    <th>
                        Correo
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    if (item.TipoPersonaId == 2)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PrimerNombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SegundoNombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PrimerApellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SegundoApellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdentificadorId)
                            </td>
                            <td>
                                @if (item.Sexo == "M")
                                {
                                    <p>M</p>
                                }
                                else
                                {
                                    <p>F</p>
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Correo)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.PersonaId">Editar</a> |
                                <a asp-action="Details" asp-route-id="@item.PersonaId">+Informaci&oacute;n</a> |
                                <a asp-action="Delete" asp-route-id="@item.PersonaId" style="color:red;">Borrar</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>